apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo
  labels:
    app: aksdemo
spec:
  replicas: 1
  template:
    metadata:
      name: aksdemo
      labels:
        app: aksdemo
    spec:
      containers:
      - name: aksdemo
        image: demoimagereg.azurecr.io/demoapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80      
          name: aksdemo
      restartPolicy: Always
  selector:
    matchLabels:
      app: aksdemo

---
apiVersion: v1
kind: Service
metadata:
  name: aksdemo  
  labels:
    app: aksdemo
spec:
  ports:
    - port: 80
  selector:
    app: aksdemo
  type: LoadBalancer
  